### ISSUE TITLE
Mod Doesn't work

### ISSUE THREAD

**Issue by jackhoss** [LePetitJayJay/Victoria-2-Anime-Mod#2]
I'm using the GFM verison and to get it to work kind of i had to replace the flag and interface files within GFM itself with the ones from the flag mod. Of course doing this messed up alot of other images within GFM so i didn't stick with this.

Any idea what could be making it not work? Im only using GFM and this mod and i have the .mod file inside the mod folder.

**Comment by LePetitJayJay** [comment]
Maybe delete gfx folder on documents/paradox interactive/victoria 2/GFM, then see if the flags have been correctly replaced when you turned both GFM and the Animega on.

**Comment by jackhoss** [comment]
> Maybe delete gfx folder on documents/paradox interactive/victoria 2/GFM, then see if the flags have been correctly replaced when you turned both GFM and the Animega on.

No luck

**Comment by LePetitJayJay** [comment]
if that didn't fix it then I don't really know what's wrong, it should of worked when you have gfx folder on documents cleaned before launching the mod + animega together (don't launch the mod only first and then + animega on a second launch)

The one issue I knew with vic2 mechanism is that if you replace flags then you'll have to delete the gfx on documents before launching, otherwise the new flags won't show.

If you still can't figure it out I could probably change the .mod file later and see if that'll fix the issue for you.

**Comment by jackhoss** [comment]
> 

I got it working, i just had a duplicate file inside the GFM animega file which caused the game unable to find the GFX file

**Comment by LePetitJayJay** [comment]
ah alright, case closed then
